# Generated by Django 5.2.6 on 2025-11-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_exercise_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
